### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by trnxdev** [trnxdev/zigd#2]
- [ ] Add zigd specific config option to not auto install zig versions. (see zigdemu.zig)
- [ ] Stop using the libarchive option and instead use a zig library to extract archives
- [ ] Add windows support
- [ ] Add zigdzlsemu?
